# Generated by Django 4.2.1 on 2023-05-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('houseNumber', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayOfWeek', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('openingTime', models.TimeField()),
                ('closingTime', models.TimeField()),
                ('isClosed', models.BooleanField(default=False)),
                ('isSpecialTime', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('dayOfWeek', 'openingTime', 'closingTime', 'isClosed', 'isSpecialTime')},
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.ManyToManyField(to='StoreAPI.address')),
                ('openingHours', models.ManyToManyField(to='StoreAPI.openinghours')),
            ],
        ),
    ]
