# Generated by Django 4.2.1 on 2023-05-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghours',
            name='dayOfWeek',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')]),
        ),
    ]
